### ISSUE TITLE
Support multiple directories

### ISSUE THREAD

**Issue by mbloms** [Lakshmipathi/dduper#25]
Multiple files are supported with `--files`, but only one directory using `--dir`. This is quite limiting when deduplicating multiple directories.

**Comment by Lakshmipathi** [comment]
Are you referring to subdirectories (/mnt/d1/d2) or two different directories (/mnt/d1 /mnt/d2) ?  There is `--dir --recurse` option to de-duplicate sub-directories.

**Comment by Lakshmipathi** [comment]
I think you meant `--dir /mnt/d1 /mnt/d2` . That's nice option. Let me add them.

**Comment by mbloms** [comment]
> I think you meant `--dir /mnt/d1 /mnt/d2` . That's nice option. Let me add them.

Exactly what I meant!

**Comment by Lakshmipathi** [comment]
Added this option and CI jobs running for PR: https://github.com/Lakshmipathi/dduper/pull/32

**Comment by Lakshmipathi** [comment]
Job passed: https://gitlab.com/giis/dduper/-/pipelines/181167974  Marking this as resolved.
