### ISSUE TITLE
Question: What do you mean by "offline"?

### ISSUE THREAD

**Issue by mbloms** [Lakshmipathi/dduper#26]
It seems like the file system has to be mounted in order for dduper to work. Is it safe to use the file system while dduper is running? What do you mean by "offline"?

**Comment by Lakshmipathi** [comment]
Yes, its kind of misleading - From https://btrfs.wiki.kernel.org/index.php/Deduplication 

```
Out of band / batch deduplication is deduplication done outside of the write path. We've sometimes called it offline deduplication, but that can confuse people: btrfs dedup involves the kernel and always happens on mounted filesystems. To use out-of-band deduplication, you run a tool which searches your filesystem for identical blocks, and then deduplicates them. 
```

I'll change it to `Out of band` and update the docs.

**Comment by Lakshmipathi** [comment]
Updated the README.md file.
