### ISSUE TITLE
Add information about `dump-csum` to README

### ISSUE THREAD

**Issue by rggjan** [Lakshmipathi/dduper#29]
Just tried it out and got lots of messages like:

`btrfs inspect-internal: unknown token 'dump-csum'`.

There should be a text somewhere on how to apply a patch or get a version of btrfs-progs which supports the `dump-csum` command in the README

**Comment by Lakshmipathi** [comment]
How did you install it?  `dump-csum` related info can be found at https://github.com/Lakshmipathi/dduper/blob/master/INSTALL.md

**Comment by rggjan** [comment]
I ran the pre-built binary, but missed the copying of `btrfs.static` step...

Just realized that must be where the patch lives. Thanks :)

**Comment by Lakshmipathi** [comment]
Yes, let me highlight `btrfs.static` step :)  - it might be easy to overlook that one. thanks!

**Comment by rggjan** [comment]
Perfect, and thanks a lot for the great tool!
