### ISSUE TITLE
Docker - unable to open /dev/sdX

### ISSUE THREAD

**Issue by christian2022** [Lakshmipathi/dduper#43]
I'm trying to run dduper from Docker with 
```
 sudo docker run -it --device /dev/sdf -v /media/data:/media/data laks/dduper dduper --device /dev/sdf --dir /media/data/media/Ixus --recurse --analyze
```
`/media/data` is the mountpoint for `/dev/sdf `with btrfs filesystem.

The output for all files is more or less like:
```
[Analyzing] /media/data/media/Ixus/103___12/IMG_0431.JPG:/media/data/media/Ixus/144___05/IMG_3098.JPG bad tree block 21676032, bytenr mismatch, want=21676032, have=0
ERROR: cannot read chunk root
unable to open /dev/sdf
bad tree block 21676032, bytenr mismatch, want=21676032, have=0
ERROR: cannot read chunk root
unable to open /dev/sdf
Perfect match :  /media/data/media/Ixus/103___12/IMG_0431.JPG /media/data/media/Ixus/144___05/IMG_3099.JPG
```
The volume is fine and healthy. All files can be read.
I assume there's something going wrong with accessing /dev/sdf from within the container.
Any ideas?

**Comment by Lakshmipathi** [comment]
>ERROR: cannot read chunk root

That points to possibly corrupted BTRFS chunk root. Can you try running for "btrfs check" and verify that it doesn't report any errors before running dduper?

`btrfs check --readonly /dev/sdf`

**Comment by christian2022** [comment]
Thanks for the quick response! I've already run `btrfs scrub` before which reported 2 errors on one disk that have been corrected, so it should be fine. I've now started `btrfs check --readonly --force /dev/sdf` - `--force` because it's mounted. Is running now, but will take quite some time.

**Comment by christian2022** [comment]
In fact there were issues with screwed up transanctions. I was not able to resolve them, getting support for btrfs seems impossible. I reformatted the drive and will retry.
Closing as it's probably not related to dduper.
