### ISSUE TITLE
Btrfs-progs patch issue - Hunk #1 FAILED at 158.

### ISSUE THREAD

**Issue by 3vi1** [Lakshmipathi/dduper#46]
I just discovered dduper today and was trying to set it up, but ran into the following issue while cut/pasting the INSTALL.md steps to apply the btrfs-progs patch.

```
08:23:58 evil@H510 ~/src/dduper/btrfs-progs» patch -p1 < ../patch/btrfs-progs-v5.6.1/0001-Print-csum-for-a-given-file-on-stdout.patch
patching file Makefile
Hunk #1 FAILED at 158.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
patching file cmds/commands.h
patching file cmds/inspect-dump-csum.c
patching file cmds/inspect.c
Hunk #1 succeeded at 667 (offset -3 lines).
```

Makefile.rej:

```
08:28:14 evil@H510 ~/src/dduper/btrfs-progs» cat Makefile.rej 
--- Makefile
+++ Makefile
@@ -158,7 +158,8 @@ cmds_objects = cmds/subvolume.o cmds/filesystem.o cmds/device.o cmds/scrub.o \
               cmds/rescue-super-recover.o \
               cmds/property.o cmds/filesystem-usage.o cmds/inspect-dump-tree.o \
               cmds/inspect-dump-super.o cmds/inspect-tree-stats.o cmds/filesystem-du.o \
-              mkfs/common.o check/mode-common.o check/mode-lowmem.o
+              mkfs/common.o check/mode-common.o check/mode-lowmem.o \
+              cmds/inspect-dump-csum.o
 libbtrfs_objects = send-stream.o send-utils.o kernel-lib/rbtree.o btrfs-list.o \
                   kernel-lib/radix-tree.o extent-cache.o extent_io.o \
                   crypto/crc32c.o common/messages.o \
```

Looking at the Makefile, it looks like more cmds_objects have been added since the original patch.  I manually added cmds/inspect-dump-csum.o to my makefile to workaround this, but thought you'd want to know to so that you can update the patch.

**Comment by 3vi1** [comment]
Looks like the make step on btrfs-progs still doesn't work after doing this.

`make: *** No rule to make target 'ctree.h', needed by 'cmds/inspect-dump-csum.o'.  Stop.`

Perhaps more changes since the patch?

**Comment by 3vi1** [comment]
Looking at the other files, I found the issue was that the include in cmds/inspect-dump-csum.c now needs to contain the path (i.e. '#include "kernel-shared/ctree.h"' instead of '#include "ctree.h"'.  There are four or five other includes in that file which needed to be updated as well.

**Comment by Lakshmipathi** [comment]
hey @3vi1 , Yes, recently (a month or so back) GitLabCI started to fail on btrfs-build stage. You are right, dduper needs to  be updated to catch up with btrfs-progs. 

>Those updates appear to be the only changes needed to get btrfs-progs compiled. Running tests now!
Great! Could you please send those changes as PR. I'll merge and check the CI results? thanks

**Comment by 3vi1** [comment]
Submitted:  https://github.com/Lakshmipathi/dduper/pull/47

**Comment by Lakshmipathi** [comment]
Now CI pipeline also passed: https://gitlab.com/giis/dduper/-/pipelines/234047940 Thanks @3vi1 for the help :+1:
