### ISSUE TITLE
port to python3

### ISSUE THREAD

**Issue by illwieckz** [Lakshmipathi/dduper#6]
This code seems to use python2.

1. Distros are removing it,
2. I had to create a python2 virtualenv to be able to install `beautifultable`, but the one installed via `pip` does not work:

```
(venv) root@box:~/dduper# ./dduper --device /dev/mapper/something --dir /mnt/something
Traceback (most recent call last):
  File "./dduper", line 28, in <module>
    from beautifultable import BeautifulTable
  File "/root/dduper/venv/lib/python2.7/site-packages/beautifultable/__init__.py", line 5, in <module>
    from .beautifultable import (  # noqa F401
  File "/root/dduper/venv/lib/python2.7/site-packages/beautifultable/beautifultable.py", line 36, in <module>
    from .utils import (
  File "/root/dduper/venv/lib/python2.7/site-packages/beautifultable/utils.py", line 39
    def ensure_type(value, *types, varname="value"):
                                         ^
SyntaxError: invalid syntax
```

Sadly, this makes this tool unusable on my end.

**Comment by tushar-nitave** [comment]
Can I work on this issue? To convert it to python3

**Comment by illwieckz** [comment]
I'm not planning to do it myself, so let's see what @Lakshmipathi has to say on it.

**Comment by Lakshmipathi** [comment]
@illwieckz thanks for reporting the issue. Yes, I tested only with python2.x not python3. I was planning to migrate to python3 little later (probably few months later). 

@tushar-nitave sure If you have free time, please feel free to work on this and send a PR. I'll be happy to review and merge.

**Comment by tushar-nitave** [comment]
Sure @Lakshmipathi

**Comment by dominix** [comment]
dduper$ sudo -H pip3 install beautifultable
Requirement already satisfied: beautifultable in /usr/local/lib/python3.8/dist-packages (0.8.0)

dduper$ ./dduper --version
Traceback (most recent call last):
  File "./dduper", line 28, in <module>
    from beautifultable import BeautifulTable
ImportError: No module named beautifultable


I am missing something ?

**Comment by Lakshmipathi** [comment]
Hi @dominix , Could you please  get latest code `git pull`and try again? Just now merged python3 related changes.

**Comment by Lakshmipathi** [comment]
`pip3 install -r requirements.txt`  should install required python dependencies

**Comment by dominix** [comment]
nice !
./dduper --version
dduper 0.02

**Comment by Lakshmipathi** [comment]
Thanks for the report and patches, I'll go ahead and mark this as resolved.
